/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-07-04 00:52:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signupForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/sts-bundle/workspaceProject06.12/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/sts-bundle/workspaceProject06.12/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/member/../includes/header.jsp", Long.valueOf(1688431948103L));
    _jspx_dependants.put("/WEB-INF/views/member/../includes/footer.jsp", Long.valueOf(1688015712255L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1686628228862L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/header.css\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div id=\"snbwrap\">\r\n");
      out.write("		<div id=\"snb\">\r\n");
      out.write("        	<div id =\"snb-logo\" class=\"libSite dropdown\">\r\n");
      out.write("           		<a href=\"/\" class=\"button\">바로가기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("            <div id =\"siteMenu\">\r\n");
      out.write("	            <ul id =\"gnb1\">\r\n");
      out.write("	                <li>\r\n");
      out.write("	                    <a href=\"/board/list\"><span class=\"menu-item\">게시판</span></a>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("   		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"headerwrap\">\r\n");
      out.write("		 <div id=\"header\">\r\n");
      out.write("            <div id=\"header-logo\">\r\n");
      out.write("                <div id=\"header1\">\r\n");
      out.write("                    <a href=\"/\">\r\n");
      out.write("                    	<img src=\"/resources/image/logo.png\" alt=\"#\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"header2\">\r\n");
      out.write("                    <div id=\"searchBox\" class=\"searchBoxwrap\">\r\n");
      out.write("                        <div class=\"searchBox\">\r\n");
      out.write("                            <label for =\"topSearchType\" class=\"blind\">검색유형 선택</label>\r\n");
      out.write("                            <select name=\"topSearchType\" id=\"topSearchType\" class=\"searchSelect\">\r\n");
      out.write("                                <option value=\"Book\" selected=\"selected\">소장자료</option>\r\n");
      out.write("                                <option value=\"HOME\">홈페이지</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <div class=\"keywordInput\">\r\n");
      out.write("                               <!--  <label for =\"topSearchKeyword\" class=\"blind\">검색어 입력</label> -->\r\n");
      out.write("                                <input type=\"hidden\" title=\"검색어 입력\" id=\"topSearchKeyword\" name=\"searchKeyword\"\r\n");
      out.write("                                autocomplete=\"off\" placeholder=\"검색어 입력\">\r\n");
      out.write("                            </div>\r\n");
      out.write("           					<a href=\"#search\" id=\"topSearchBtn\" title=\"검색\" class=\"btnSearch\">\r\n");
      out.write("           						<span class=\"blind\">검색</span>\r\n");
      out.write("           					</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> \r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"header3\">\r\n");
      out.write("                    <div class=\"wrapper_sub\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav id=\"nav\">\r\n");
      out.write("                <ul id =\"gnb\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">도서관안내</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">도서관소개</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">자료검색</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">통합자료검색</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">도서정보</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">신착도서목록</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">문화마당</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">도서관달력</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">이용자마당</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">내서재</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">기본정보</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/signup.css\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script src=\"/resources/js/test.js\" defer></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("	$(\"#phone1\").on(\"input\", function(e){\r\n");
      out.write("		let phone1 = $(this).val();\r\n");
      out.write("		if(phone1.length ===3){\r\n");
      out.write("			$(\"#phone2\").focus();\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#phone2\").on(\"input\", function(e){\r\n");
      out.write("		let phone2 = $(this).val();\r\n");
      out.write("		if(phone2.length ===4){\r\n");
      out.write("			$(\"#phone3\").focus();\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#phone3\").on(\"input\", function(e){\r\n");
      out.write("		let phone3 = $(this).val();\r\n");
      out.write("		if($(\"#phone1\").val().length ===3 && $(\"#phone2\").val().length === 4 && $(\"#phone3\").val().length === 4){\r\n");
      out.write("			$(\"#send\").attr(\"style\", \"background-color: #FFFFFF; color:#0068FF; cursor: pointer;\");\r\n");
      out.write("			$(\"#send\").attr(\"disabled\", false);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#signup__button\").on(\"click\", function(e) {\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		if(isValid()) {\r\n");
      out.write("			$(\"form\").submit();\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	function isValid(){\r\n");
      out.write("		let useremail = $(\"#userid\").val();\r\n");
      out.write("		let username = $(\"#username\").val();\r\n");
      out.write("		let password1 = $(\"#pw1\").val();\r\n");
      out.write("		let password2 = $(\"#pw2\").val();\r\n");
      out.write("		let location = $(\"#location\").val();\r\n");
      out.write("		let genderWoman = $(\"#gender__woman\").is(\":checked\");\r\n");
      out.write("		let genderMan = $(\"#gender__man\").is(\":checked\");\r\n");
      out.write("	\r\n");
      out.write("		$(\"#error__email\").text(\"\");\r\n");
      out.write("		$(\"#error__name\").text(\"\");\r\n");
      out.write("		$(\"#error__password1\").text(\"\");\r\n");
      out.write("		$(\"#error__password2\").text(\"\");\r\n");
      out.write("		$(\"#error__location\").text(\"\");\r\n");
      out.write("		$(\"#error__gender\").text(\"\");\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		var regExp = /^[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*\\.[a-zA-Z]{2,3}$/; //이메일 정규식\r\n");
      out.write("		if(regExp.test(useremail) === false) {\r\n");
      out.write("			$(\"#error__email\").text(\"이메일이 올바르지 않습니다.\");\r\n");
      out.write("			$(\"#userid\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(username === \"\") {\r\n");
      out.write("			$(\"#error__name\").text(\"이름이 올바르지 않습니다.\");\r\n");
      out.write("			$(\"#username\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(password1 === \"\") {\r\n");
      out.write("			$(\"#error__password1\").text(\"비밀번호를 입력해 주세요.\");\r\n");
      out.write("			$(\"#pw1\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(password2 === \"\") {\r\n");
      out.write("			$(\"#error__password2\").text(\"비밀번호를 입력해 주세요.\");\r\n");
      out.write("			$(\"#pw2\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(password1 !== password2) {\r\n");
      out.write("			$(\"#error__password1\").text(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("			$(\"#error__password2\").text(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("			$(\"#pw2\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		let validLocations = [\"서울\",\"경기도\",\"인천\",\"대전\",\"광주\",\"대구\",\"부산\",\"울산\",\"충청도\",\"강원도\",\"전라도\",\"경상도\",\"제주도\"];\r\n");
      out.write("		if(!validLocations.includes(location)) {\r\n");
      out.write("			$(\"#error__location\").text(\"지역을 선택해 주세요.\");\r\n");
      out.write("			$(\"#location\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(genderWoman === false && genderMan === false) {\r\n");
      out.write("			$(\"#error__gender\").text(\"성별을 선택해 주세요.\");\r\n");
      out.write("			$(\"#gender__woman\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	};\r\n");
      out.write("	/*\r\n");
      out.write("	$(\"#send\").on(\"click\",function(e){ // 누르면 번호가 온다\r\n");
      out.write("		getToken();\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#finished\").on(\"click\",function(e){ // 문자를 받았다고 가정하고 번호 입력누르면 완료\r\n");
      out.write("		getTimerIntervalConfirm();\r\n");
      out.write("	});\r\n");
      out.write("	*/\r\n");
      out.write("	/*\r\n");
      out.write("	$(\"#send\").on(\"click\",function(e){\r\n");
      out.write("		memberService.getToken($(\"#token\"),$(\"#send\"),$(\"#finished\"),$(\"#timer\"));\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#finished\").on(\"click\",function(e){\r\n");
      out.write("		memberService.getTimerIntervalConfirm($(\"#finished\"), $(\"#signup__button\"));\r\n");
      out.write("	});\r\n");
      out.write("	*/\r\n");
      out.write("	let timer= new Timer();\r\n");
      out.write("	$(\"#send\").on(\"click\",function(e){\r\n");
      out.write("		timer.getToken($(\"#token\"),$(\"#send\"),$(\"#finished\"),$(\"#timer\"));\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#finished\").on(\"click\",function(e){\r\n");
      out.write("		timer.getTimerIntervalConfirm($(\"#finished\"), $(\"#signup__button\"));\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function getToken(){\r\n");
      out.write("		let token = String(Math.floor(Math.random()*1000000)).padStart(6,\"0\") //1~999999사이의 숫자 6가지를 랜덤으로 뽑는다.\r\n");
      out.write("		$(\"#token\").text(token);\r\n");
      out.write("		$(\"#send\").attr(\"style\", \"background-color: #FFFFFF; cursor:default;\");\r\n");
      out.write("		$(\"#send\").attr(\"disabled\", true);\r\n");
      out.write("		$(\"#finished\").attr(\"style\", \"background-color: #0068FF; color: #FFFFFF; cursor:pointer;\");\r\n");
      out.write("		$(\"#finished\").attr(\"disabled\", false);\r\n");
      out.write("		getTimerInterval();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	let interval;\r\n");
      out.write("	\r\n");
      out.write("	function getTimerInterval(){\r\n");
      out.write("		let time = 179;\r\n");
      out.write("		interval = setInterval(() => {\r\n");
      out.write("			if(time >= 0) {\r\n");
      out.write("				let minutes =Math.floor(time / 60);\r\n");
      out.write("				let seconds = time % 60;\r\n");
      out.write("				$(\"#timer\").text(minutes + \":\" + String(seconds).padStart(2,\"0\"));\r\n");
      out.write("				time -=1;\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\"#token\").text(\"000000\");\r\n");
      out.write("				$(\"#send\").attr(\"style\",\"\");\r\n");
      out.write("				$(\"#send\").attr(\"disabled\", true);\r\n");
      out.write("				$(\"#timer\").attr(\"3:00\");\r\n");
      out.write("				$(\"#finished\").attr(\"style\",\"\");\r\n");
      out.write("				$(\"#finished\").attr(\"disabled\", true);\r\n");
      out.write("				clearInterval(interval);\r\n");
      out.write("			}\r\n");
      out.write("		}, 1000);\r\n");
      out.write("	}\r\n");
      out.write("	function getTimerIntervalConfirm() {\r\n");
      out.write("		clearInterval(interval)\r\n");
      out.write("		$(\"#finished\").attr(\"style\", \"background-color: #FFFFFF; cursor:default;\");\r\n");
      out.write("		$(\"#finished\").attr(\"disabled\", true);\r\n");
      out.write("		$(\"#finished\").text(\"인증완료\");\r\n");
      out.write("		alert(\"인증이 완료되었습니다.\");\r\n");
      out.write("		$(\"#signup__button\").attr(\"style\", \"background-color: #FFFFFF; color:#2c3639; border:1px solid #2x3639; cursor:default;\");\r\n");
      out.write("		$(\"#signup__button\").attr(\"disabled\", false);\r\n");
      out.write("	}\r\n");
      out.write("});	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper_signup\">\r\n");
      out.write("	<div class=\"signup\">\r\n");
      out.write("		<h1>회원가입</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("    <div class=\"main_body\">\r\n");
      out.write("        <header class=\"wrap__title\"></header>\r\n");
      out.write("        <form role=\"form\" action=\"/member/signup\" method=\"post\">\r\n");
      out.write("            <main class=\"wrap__main\">\r\n");
      out.write("                <input class=\"main__input\" id=\"userid\" type=\"email\" name=\"userid\" placeholder=\"이메일을 입력해주세요.\"/>\r\n");
      out.write("                <div class=\"error\" id=\"error__email\"></div>\r\n");
      out.write("                <input class=\"main__input\" id=\"username\" type=\"text\" name=\"username\" maxlength=\"8\" placeholder=\"이름을 입력해 주세요\"/>\r\n");
      out.write("                <div class=\"error\" id=\"error__name\"></div>\r\n");
      out.write("                <input class=\"main__input\" id=\"pw1\" type=\"password\" name=\"userpw\" maxlength=\"20\" placeholder=\"비밀번호를 입력해 주세요\"/>\r\n");
      out.write("                <div class=\"error\" id=\"error__password1\"></div>\r\n");
      out.write("                <input class=\"main__input\" id=\"pw2\" type=\"password\" maxlength=\"20\" placeholder=\"비밀번호를 다시 입력해 주세요\"/>\r\n");
      out.write("                <div class=\"error\" id=\"error__password2\"></div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"wrap__phone\">\r\n");
      out.write("                    <input class=\"phone__input\" id=\"phone1\" type=\"text\" maxlength=\"3\" />\r\n");
      out.write("                    <span>-</span>\r\n");
      out.write("                    <input class=\"phone__input\" id=\"phone2\" type=\"text\" maxlength=\"4\" />\r\n");
      out.write("                    <span>-</span>\r\n");
      out.write("                    <input class=\"phone__input\" id=\"phone3\" type=\"text\" maxlength=\"4\" />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"wrap__auth\">\r\n");
      out.write("                    <div id=\"auth__target\">\r\n");
      out.write("                        <span id=\"token\">000000</span>\r\n");
      out.write("                        <button class=\"auth_button\" id=\"send\" type=\"button\" disabled=\"disabled\" >\r\n");
      out.write("                            인증번호 전송\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"wrap__auth\">\r\n");
      out.write("                    <div id=\"auth__timer\">\r\n");
      out.write("                        <span id=\"timer\">3:00</span>\r\n");
      out.write("                        <button class=\"auth_button\" id=\"finished\" type=\"button\" disabled=\"disabled\" >\r\n");
      out.write("                            인증완료\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <select class=\"select__box\" id=\"location\" name=\"location\">\r\n");
      out.write("                    <option disabled=\"disabled\" selected=\"true\">지역을 선택하세요</option>\r\n");
      out.write("                    <option value=\"서울\">서울</option>\r\n");
      out.write("                    <option value=\"경기도\">경기도</option>\r\n");
      out.write("                    <option value=\"인천\">인천</option>\r\n");
      out.write("                    <option value=\"대전\">대전</option>\r\n");
      out.write("                    <option value=\"광주\">광주</option>\r\n");
      out.write("                    <option value=\"대구\">대구</option>\r\n");
      out.write("                    <option value=\"부산\">부산</option>\r\n");
      out.write("                    <option value=\"울산\">울산</option>\r\n");
      out.write("                    <option value=\"충청도\">충청도</option>\r\n");
      out.write("                    <option value=\"강원도\">강원도</option>\r\n");
      out.write("                    <option value=\"전라도\">전라도</option>\r\n");
      out.write("                    <option value=\"경상도\">경상도</option>\r\n");
      out.write("                    <option value=\"제주도\">제주도</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <div class=\"error\" id=\"error__location\"></div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"wrap__radio\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input class=\"radio1\" type=\"radio\" name=\"gender\" value=\"woman\" id=\"gender__woman\"/>\r\n");
      out.write("                        <span class=\"gender\">여성</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input class=\"radio2\" type=\"radio\" name=\"gender\" value=\"man\" id=\"gender__man\"/>\r\n");
      out.write("                        <span class=\"gender\">남성</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"error\" id=\"error__gender\"></div>\r\n");
      out.write("            </main>\r\n");
      out.write("            <hr/>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"wrap__confirm\">\r\n");
      out.write("                <button class=\"confirm__button\" id=\"signup__button\" type=\"submit\" disabled=\"disabled\">\r\n");
      out.write("                    가입하기\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/footer.css\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id =\"footerwrap\">\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("	       <div id=\"footer1\">\r\n");
      out.write("	       		<div id=\"footerfooter\">\r\n");
      out.write("		       		\r\n");
      out.write("		           <ul class=\"fnb\">\r\n");
      out.write("		           		<li> <a href=\"#\">개인정보처리방법</a></li>\r\n");
      out.write("	               		<li> <a href=\"#\">영상정보처리기기운영.관리방침</a></li>\r\n");
      out.write("	               		<li> <a href=\"#\">이용약관</a></li>\r\n");
      out.write("	               		<li> <a href=\"#\">이메일무단수집거부</a></li>\r\n");
      out.write("	               		<li> <a href=\"#\">찾아오는길</a></li>\r\n");
      out.write("		           </ul>\r\n");
      out.write("		           <div class=\"familySite\">\r\n");
      out.write("		           		<select name=\"relateSite\" id=\"relateSite\" title=\"유관기관 바로가기 선택\">\r\n");
      out.write("		           			<option value selected=\"selected\">유관기관 바로가기</option>\r\n");
      out.write("		           			<option value=\"#\">성남시청</option>\r\n");
      out.write("		           			<option value=\"#\">수정구청</option>\r\n");
      out.write("		           			<option value=\"#\">중원구청</option>\r\n");
      out.write("		           			<option value=\"#\">분당구청</option>\r\n");
      out.write("		           			<option value=\"#\">평생학습포털 배움</option>\r\n");
      out.write("		           			\r\n");
      out.write("		           		</select>\r\n");
      out.write("		           		<a href =\"#go\" id=\"btnRelateSite\" class=\"btnGO\" title=\"새 창 열림\">GO</a>\r\n");
      out.write("		           </div>\r\n");
      out.write("		           \r\n");
      out.write("	           </div>\r\n");
      out.write("	       </div>\r\n");
      out.write("	       <div id=\"footer2\">\r\n");
      out.write("	           <cite>\r\n");
      out.write("			           (우)13623 경기도 성남시 분당구 구미로 111(구미동) \r\n");
      out.write("			           <span class=\"tel\">Tel. 031-729-4770</span>\r\n");
      out.write("			           <span class=\"fax\"> Fax. 031-729-4779</span><br>\r\n");
      out.write("	               	Copyright © 성남시도서관사업소. All Rights Reserved.\r\n");
      out.write("	           </cite>\r\n");
      out.write("	       </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		               	");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/member/../includes/header.jsp(27,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <li>\r\n");
          out.write("                            	<a href=\"/member/logout\"><span class=\"menu-item\">로그아웃</span></a>\r\n");
          out.write("                          	</li> \r\n");
          out.write("                          	<li>\r\n");
          out.write("                            	<a href=\"/seat/main\"><span class=\"menu-item\">좌석예약</span></a>\r\n");
          out.write("                       		</li>\r\n");
          out.write("	                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                        <li>\r\n");
          out.write("	                            <a href=\"/member/login\"><span class=\"menu-item\">로그인</span></a>\r\n");
          out.write("	                        </li>\r\n");
          out.write("	                        <li>\r\n");
          out.write("	                            <a href=\"/member/signup\"><span class=\"menu-item\">회원가입</span></a>\r\n");
          out.write("	                        </li>\r\n");
          out.write("		                ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/../includes/header.jsp(77,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <span>");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("님 접속중입니다.</span>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/member/../includes/header.jsp(78,34) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${auth.username}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
