/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-07-10 07:29:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/./includes/header.jsp", Long.valueOf(1688974142286L));
    _jspx_dependants.put("/WEB-INF/views/./includes/footer.jsp", Long.valueOf(1688015712255L));
    _jspx_dependants.put("jar:file:/C:/sts-bundle/workspaceProject06.12/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1686628228862L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/header.css\">\r\n");
      out.write("\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div id=\"snbwrap\">\r\n");
      out.write("		<div id=\"snb\">\r\n");
      out.write("        	<div id =\"snb-logo\" class=\"libSite dropdown\">\r\n");
      out.write("           		<a href=\"/\" class=\"button\">바로가기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("            <div id =\"siteMenu\">\r\n");
      out.write("	            <ul id =\"gnb1\">\r\n");
      out.write("	                <li>\r\n");
      out.write("	                    <a href=\"/board/list\"><span class=\"menu-item\">게시판</span></a>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("   		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"headerwrap\">\r\n");
      out.write("		 <div id=\"header\">\r\n");
      out.write("            <div id=\"header-logo\">\r\n");
      out.write("                <div id=\"header1\">\r\n");
      out.write("                    <a href=\"/\">\r\n");
      out.write("                    	<img src=\"/resources/image/logo.png\" alt=\"#\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"header2\">\r\n");
      out.write("                    <div id=\"searchBox\" class=\"searchBoxwrap\">\r\n");
      out.write("                        <div class=\"searchBox\">\r\n");
      out.write("                            <label for =\"topSearchType\" class=\"blind\">검색유형 선택</label>\r\n");
      out.write("                            <select name=\"topSearchType\" id=\"topSearchType\" class=\"searchSelect\">\r\n");
      out.write("                                <option value=\"Book\" selected=\"selected\">소장자료</option>\r\n");
      out.write("                                <option value=\"HOME\">홈페이지</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <div class=\"keywordInput\">\r\n");
      out.write("                               <!--  <label for =\"topSearchKeyword\" class=\"blind\">검색어 입력</label> -->\r\n");
      out.write("                                <input type=\"hidden\" title=\"검색어 입력\" id=\"topSearchKeyword\" name=\"searchKeyword\"\r\n");
      out.write("                                autocomplete=\"off\" placeholder=\"검색어 입력\">\r\n");
      out.write("                            </div>\r\n");
      out.write("           					<a href=\"#search\" id=\"topSearchBtn\" title=\"검색\" class=\"btnSearch\">\r\n");
      out.write("           						<span class=\"blind\">검색</span>\r\n");
      out.write("           					</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> \r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"header3\">\r\n");
      out.write("                    <div class=\"wrapper_sub\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav id=\"nav\">\r\n");
      out.write("                <ul id =\"gnb\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">도서관안내</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">도서관소개</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">자료검색</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">통합자료검색</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">도서정보</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">신착도서목록</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">문화마당</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">도서관달력</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">이용자마당</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">내서재</a>\r\n");
      out.write("                        <ul id=\"lnb\">\r\n");
      out.write("                            <li><a href=\"#\">기본정보</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Home</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/home.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/slide.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/contents.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/jquery.bxslider.css\">\n");
      out.write("<link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("\n");
      out.write("<!-- <script src=\"/resources/js/jquery.cookie.min.js\" ></script>  -->\n");
      out.write("\n");
      out.write("<script src=\"/resources/js/jquery.bxslider.min.js\" defer></script>\n");
      out.write("<script src=\"/resources/js/home_calendar.js\" ></script>\n");
      out.write("<script src=\"/resources/js/app.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(function(){\n");
      out.write("	let msg ='");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("	if(msg === \"\"){\n");
      out.write("		return;\n");
      out.write("	} \n");
      out.write("	let txt;\n");
      out.write("	if(msg === \"logout\") {\n");
      out.write("		txt=\"로그아웃 되었습니다.\";\n");
      out.write("	}\n");
      out.write("	alert(txt);\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<!-- <div class=\"wrapper_main\">\n");
      out.write("	<p><h1>Spring project 메인 화면입니다.</h1>\n");
      out.write("</div> -->\n");
      out.write("<body>\n");
      out.write("   <!--  <div id=\"popup\">\n");
      out.write("        <div id=\"popup-img\">\n");
      out.write("            <img src=\"./images/popup-img.jpg\">\n");
      out.write("        </div>\n");
      out.write("        <div id=\"btn-area\">\n");
      out.write("            <input type=\"checkbox\" id=\"popup-chk\" style=\"width:25px;height:25px;\">\n");
      out.write("            <span  style=\"font-size: 20px;\"> 7일동안 보지 않기</span>\n");
      out.write("        </div>\n");
      out.write("    </div>    \n");
      out.write("         -->\n");
      out.write("    <div id =\"wrap\">\n");
      out.write("        \n");
      out.write("       \n");
      out.write("\n");
      out.write("        <div id=\"slide\">\n");
      out.write("           <div id=\"slide_contents\">\n");
      out.write("            	<img src=\"/resources/image/main.jpg\" alt=\"슬라이드1\">\n");
      out.write("                <img src=\"/resources/image/main.jpg\" alt=\"슬라이드2\">\n");
      out.write("                <img src=\"/resources/image/main.jpg\" alt=\"슬라이드3\">\n");
      out.write("            </div> \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"content\">\n");
      out.write("            <div id=\"cont1\">\n");
      out.write("                <ul class=\"shortcut\">\n");
      out.write("                    <li class=\"svc1\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"희망도서신청\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc2\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"전자책\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc3\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"오디오북\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc4\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"전자잡지\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc5\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"스마트도서관\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc6\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"열람실좌석현황\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc7\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"문화행사\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc8\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"수강신청\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc9\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"북스타트사업\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"svc10\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"ico\"></i>\n");
      out.write("                            \"독서동아리\"\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div> \n");
      out.write("            <div id=\"cont2\">\n");
      out.write("                <div id =\"cont2-1\">\n");
      out.write("                    <div id =\"cont2-1-1\">\n");
      out.write("                        <div id=\"time\">\n");
      out.write("                            <div id =\"time-btn\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    도서관 이용시간 안내\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div id =\"tab-time\">\n");
      out.write("                                <span>\n");
      out.write("                                    유아 및 어린이가족열람실<br>\n");
      out.write("                                    -하절기(3월~10월) 9:00~20:00<br>\n");
      out.write("                                    -동절기(11월~2월) 9:00~18:00<br>\n");
      out.write("                                    -주말(연중) 9:00~18:00<br>\n");
      out.write("                                     일반열람식(평일 및 주말) 09:00~20:00<br>\n");
      out.write("                                     *1,3주 월요일 및 명절연휴 전체휴관<br>\n");
      out.write("                                     *매주 월요일 및 법정공휴일 자료실 휴실\n");
      out.write("                                </span>\n");
      out.write("                               \n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div id =\"cont2-1-2\">\n");
      out.write("                    	<div class=\"title\">이용문의 안내</div>\n");
      out.write("                    	<div class=\"telimg\">\n");
      out.write("							<img src=\"/resources/image/telephone.png\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"tel\">\n");
      out.write("							<p>\n");
      out.write("								\"Tel:031-729-4770\"\n");
      out.write("								<br>\n");
      out.write("								\"Fax:031-729-4779\"\n");
      out.write("							</p>\n");
      out.write("						</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div id =\"cont2-1-3\">\n");
      out.write("                   		<div class=\"locaption\">오시는길</div>\n");
      out.write("                    	<div class=\"locaptionimg\">\n");
      out.write("							<img src=\"/resources/image/locaption.png\">\n");
      out.write("						</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div id =\"cont2-1-4\">\n");
      out.write("                   		<div class=\"faq\">FAQ</div>\n");
      out.write("                    	<div class=\"faqimg\">\n");
      out.write("							<img src=\"/resources/image/faq.png\">\n");
      out.write("						</div>\n");
      out.write("                    </div> \n");
      out.write("                </div>\n");
      out.write("                <div id =\"cont2-2\">\n");
      out.write("                    <div id=\"tab\">\n");
      out.write("                        <div id =\"tab-btn\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                공지사항\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        <div id =\"tab-contents\">\n");
      out.write("                            <div id =\"notice\">\n");
      out.write("                                <ul>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <span>동화팩 읽어주기 안내</span>\n");
      out.write("                                            <span>2023.12.01</span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <span>무지개도서관 휴관일 안내</span>\n");
      out.write("                                            <span>2023.11.01</span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <span>만들기 체험행사</span>\n");
      out.write("                                            <span>2023.10.01</span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <span>문화가 있는 날 행사 안내</span>\n");
      out.write("                                            <span>2023.09.01</span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li>\n");
      out.write("                                        <a href=\"#\">\n");
      out.write("                                            <span>문화의 날 행사 안내</span>\n");
      out.write("                                            <span>2023.08.01</span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div> \n");
      out.write("            <div id=\"cont3\">\n");
      out.write("                <div id=\"book\">\n");
      out.write("                    <div class =\"books\">\n");
      out.write("                        <span>추천도서</span>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                  \n");
      out.write("                    <div class=\"bookImg\">\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book1.jpg\" alt=\"베르베르씨\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book2.jpg\" alt=\"나는 왜 이렇게 웃긴가\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book3.jpg\" alt=\"초초 난난\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book4.jpg\" alt=\"세이노의 가르침\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book5.jpg\" alt=\"원피스\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book6.jpg\" alt=\"불편한 편의점\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book7.jpg\" alt=\"우습지 않다\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book8.jpg\" alt=\"역행자\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book9.jpg\" alt=\"채소 과일식\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                        <span class=\"cover\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <img src=\"/resources/image/book10.jpg\" alt=\"미래과거시제\"> \n");
      out.write("                            </a>\n");
      out.write("                        </span>\n");
      out.write("                    </div> \n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                <div id=\"cont3-2\">\n");
      out.write("                    <table id=\"calendar\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th><input name=\"preMon\" type=\"button\" value=\"<\"></th>\n");
      out.write("                                <th colspan=\"5\" class=\"year_mon\"></th>\n");
      out.write("                                <th><input name=\"nextMon\" type=\"button\" value=\">\"></th>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>일</th>\n");
      out.write("                                <th>월</th>\n");
      out.write("                                <th>화</th>\n");
      out.write("                                <th>수</th>\n");
      out.write("                                <th>목</th>\n");
      out.write("                                <th>금</th>\n");
      out.write("                                <th>토</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("            </div> \n");
      out.write("            \n");
      out.write("        </div> \n");
      out.write("       \n");
      out.write("    </div>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/footer.css\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id =\"footerwrap\">\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("	       <div id=\"footer1\">\r\n");
      out.write("	       		<div id=\"footerfooter\">\r\n");
      out.write("		       		\r\n");
      out.write("		           <ul class=\"fnb\">\r\n");
      out.write("		           		<li> <a href=\"#\">개인정보처리방법</a></li>\r\n");
      out.write("	               		<li> <a href=\"#\">영상정보처리기기운영.관리방침</a></li>\r\n");
      out.write("	               		<li> <a href=\"#\">이용약관</a></li>\r\n");
      out.write("	               		<li> <a href=\"#\">이메일무단수집거부</a></li>\r\n");
      out.write("	               		<li> <a href=\"#\">찾아오는길</a></li>\r\n");
      out.write("		           </ul>\r\n");
      out.write("		           <div class=\"familySite\">\r\n");
      out.write("		           		<select name=\"relateSite\" id=\"relateSite\" title=\"유관기관 바로가기 선택\">\r\n");
      out.write("		           			<option value selected=\"selected\">유관기관 바로가기</option>\r\n");
      out.write("		           			<option value=\"#\">성남시청</option>\r\n");
      out.write("		           			<option value=\"#\">수정구청</option>\r\n");
      out.write("		           			<option value=\"#\">중원구청</option>\r\n");
      out.write("		           			<option value=\"#\">분당구청</option>\r\n");
      out.write("		           			<option value=\"#\">평생학습포털 배움</option>\r\n");
      out.write("		           			\r\n");
      out.write("		           		</select>\r\n");
      out.write("		           		<a href =\"#go\" id=\"btnRelateSite\" class=\"btnGO\" title=\"새 창 열림\">GO</a>\r\n");
      out.write("		           </div>\r\n");
      out.write("		           \r\n");
      out.write("	           </div>\r\n");
      out.write("	       </div>\r\n");
      out.write("	       <div id=\"footer2\">\r\n");
      out.write("	           <cite>\r\n");
      out.write("			           (우)13623 경기도 성남시 분당구 구미로 111(구미동) \r\n");
      out.write("			           <span class=\"tel\">Tel. 031-729-4770</span>\r\n");
      out.write("			           <span class=\"fax\"> Fax. 031-729-4779</span><br>\r\n");
      out.write("	               	Copyright © 성남시도서관사업소. All Rights Reserved.\r\n");
      out.write("	           </cite>\r\n");
      out.write("	       </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		               	");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/./includes/header.jsp(27,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <li>\r\n");
          out.write("                            	<a href=\"/member/logout\"><span class=\"menu-item\">로그아웃</span></a>\r\n");
          out.write("                          	</li> \r\n");
          out.write("                          	<li>\r\n");
          out.write("                            	<a href=\"/seat/main\"><span class=\"menu-item\">좌석예약</span></a>\r\n");
          out.write("                       		</li>\r\n");
          out.write("	                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                        <li>\r\n");
          out.write("	                            <a href=\"/member/login\"><span class=\"menu-item\">로그인</span></a>\r\n");
          out.write("	                        </li>\r\n");
          out.write("	                        <li>\r\n");
          out.write("	                            <a href=\"/member/signup\"><span class=\"menu-item\">회원가입</span></a>\r\n");
          out.write("	                        </li>\r\n");
          out.write("		                ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/./includes/header.jsp(77,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <span>");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("님 접속중입니다.</span>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/./includes/header.jsp(78,34) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${auth.username}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(22,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
